import {ProductState} from "store/features/product/types";
import Product4 from "assets/img/product4.png";
import Product3 from "assets/img/product3.png";
import Product2 from "assets/img/product2.png";
import Product1 from "assets/img/product1.png";
import {BrandState} from "store/features/brand/types";
import {TypeState} from "store/features/type/types";

export const initialProductsCollections: ProductState[] = [
    {
        id: 1,
        name: "Жидкость для мытья посуды",
        brandId: 1,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 300,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "Max",
        vendor: 521,
        img: Product4
    },
    {
        id: 2,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product2
    },
    {
        id: 3,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product3
    },
    {
        id: 4,
        name: "Жидкость для мытья посуды",
        brandId: 2,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 350,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "AOS",
        vendor: 523,
        img: Product1
    },
    {
        id: 5,
        name: "Жидкость для мытья посуды",
        brandId: 1,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 300,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "Max",
        vendor: 521,
        img: Product4
    },
    {
        id: 6,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product2
    },
    {
        id: 7,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product3
    },
    {
        id: 8,
        name: "Жидкость для мытья посуды",
        brandId: 2,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 350,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "AOS",
        vendor: 523,
        img: Product1
    },
    {
        id: 9,
        name: "Жидкость для мытья посуды",
        brandId: 1,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 300,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "Max",
        vendor: 521,
        img: Product4
    },
    {
        id: 10,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product2
    },
    {
        id: 11,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product3
    },
    {
        id: 12,
        name: "Жидкость для мытья посуды",
        brandId: 2,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 350,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "AOS",
        vendor: 523,
        img: Product1
    },
    {
        id: 13,
        name: "Жидкость для мытья посуды",
        brandId: 1,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 300,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "Max",
        vendor: 521,
        img: Product4
    },
    {
        id: 14,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product2
    },
    {
        id: 15,
        name: "Порошок для стирки",
        brandId: 4,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [2],
        price: 300,
        sizeType: "weight",
        sizeValue: 500,
        manufacturer: "Ariel",
        vendor: 521,
        img: Product3
    },
    {
        id: 16,
        name: "Жидкость для мытья посуды",
        brandId: 2,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 350,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "AOS",
        vendor: 523,
        img: Product1
    },
    {
        id: 17,
        name: "Жидкость для мытья посуды",
        brandId: 2,
        barcode: "32623621",
        description: "Средства бытовой химии марки Dr MAX NEW: жидкость для мытья посуды - концентрат Таежная земляника 500 мл",
        typeId: [1],
        price: 350,
        sizeType: "volume",
        sizeValue: 500,
        manufacturer: "AOS",
        vendor: 523,
        img: Product1
    },
]

export const initialBrandsCollection: BrandState[] = [
    {id: 1, name: "AOS"},
    {id: 2, name: "MAX"},
    {id: 3, name: "ARIEL"},
    {id: 4, name: "BIMAX"},
]

export const initialTypesCollection: TypeState[] = [
    {id: 1, name: "Уход за кожей"},
    {id: 2, name: "Уход за руками"},
    {id: 3, name: "Гигиена полости рта"},
    {id: 4, name: "Подарочные наборы"},
]
